feat: Add Apply Page
AI-Homepage-Practice-Frontend/AI-Homepage pull request #27
Opened 2022-05-08 09:33 UTC by suinj8

지원하기 페이지 구현하였습니다.
- 윈도우 사이즈에 따른 폰트크기 조절

[#26]

이미지 첨부
![image](https://user-images.githubusercontent.com/90179555/167290276-faefbef2-a18a-4c2d-afc3-8c092fc0eedd.png)

2022-05-09 08:32 UTC, LimEunSang requested changes
[나승훈 교수님 홈페이지](https://nlp.jbnu.ac.kr/)에 나와있는 글을 참고하면 좋겠네요.

![image](https://user-images.githubusercontent.com/86942472/167384191-5249c4cb-c820-4557-9793-f33fda726366.png)

2022-05-09 08:32 UTC, LimEunSang commented on src/pages/apply/Apply.js
> +
주석이 빠졌습니다!

2022-05-09 11:09 UTC, suinj8 commented on src/pages/apply/Apply.js
> +
@LimEunSang 수정했습니다.

2022-05-09 12:20 UTC, LimEunSang approved these changes
적극적이고 신속한 피드백 반영 바람직합니다!
LGTM!

2022-05-10 03:35 UTC, baaaam771 approved these changes
사진과 내용을 채워넣으니 훨씬 정돈되어 보입니다
LGTM

2022-05-10 14:51 UTC, euny0ung commented
LGTM!

2022-05-10 14:51 UTC, euny0ung approved these changes

2022-05-10 15:55 UTC, merged