feat: Create Researcher page
AI-Homepage-Practice-Frontend/AI-Homepage pull request #28
Opened 2022-05-09 09:32 UTC by LimEunSang

- 구성원 -> 연구원 페이지를 구현했습니다.
- 기존에 만들어 두었던 MemberPost 컴포넌트를 재활용했습니다.
- 데이터베이스에 연동할 대학원생 정보는 dummydata로 임시 저장했습니다.

![image](https://user-images.githubusercontent.com/86942472/167382261-bc206e16-a9ce-47be-9cfd-215165deae33.png)

2022-05-09 12:23 UTC, suinj8 approved these changes
전이랑 똑같네용 고생하셨습니다.
LGTM

2022-05-09 12:23 UTC, suinj8 commented on src/pages/member/Researcher.js
> +               데이터베이스와 연동할 연구원 객체 정보는 임시로 dummydata를 사용
* 추가해주세용 누락되어있네요

2022-05-09 12:23 UTC, suinj8 requested changes
별 하나만 추가해주시면 완벽합니다!

2022-05-09 12:31 UTC, LimEunSang commented on src/pages/member/Researcher.js
> +               데이터베이스와 연동할 연구원 객체 정보는 임시로 dummydata를 사용
허허.. 주석 잡는 귀신이세요?
수정했습니다.

2022-05-09 13:19 UTC, suinj8 approved these changes
LGTM!

2022-05-10 14:03 UTC, baaaam771 approved these changes
학부연구생 페이지와 거의 유사하네요
LGTM!

2022-05-10 14:52 UTC, euny0ung commented
LGTM!

2022-05-10 14:52 UTC, euny0ung approved these changes

2022-05-10 15:36 UTC, merged