Introduction page
AI-Homepage-Practice-Frontend/AI-Homepage pull request #30
Opened 2022-05-09 12:13 UTC by LimEunSang

소개 페이지를 구현했습니다.
교수님 연구실 홈페이지에 있는 pdf를 추가했습니다. 그리고 이 pdf를 화면에 출력하는 기능을 구현했습니다.
이 과정에서 새로운 react-pdf 모듈을 사용했습니다. 따라서 npm i 해줘야 실행 가능합니다.

디자인 수정이 필요해 보입니다..
pdf 다음 페이지 버튼 처음 클릭시 scroll bar 맨 위로 올라가는 버그가  있습니다. 
pdf가 간헐적으로 깨집니다.
(이슈번호 #29)

![image](https://user-images.githubusercontent.com/86942472/167407423-754e8c7e-e055-4ce5-863d-d61d0c12e619.png)

2022-05-09 12:28 UTC, suinj8 approved these changes
이슈등록해주신것만 해결하면 완벽할거 같습니다.
아마 라이브러리 문제가 아닐까 싶긴 한데..
저도 한번 알아보겠습니다.

2022-05-09 12:32 UTC, LimEunSang commented
> 이슈등록해주신것만 해결하면 완벽할거 같습니다. 아마 라이브러리 문제가 아닐까 싶긴 한데.. 저도 한번 알아보겠습니다.

예 저도 같은 생각이긴 합니다.

2022-05-09 13:19 UTC, suinj8 approved these changes
LGTM

2022-05-10 03:53 UTC, baaaam771 commented
브랜치 이름 수정이 필요해보입니다.
feature/introdution_page
이런식으로요

2022-05-10 03:54 UTC, baaaam771 requested changes
브랜치 이름 수정이 필요해보입니다.
feature/introdution_page
이런식으로요

2022-05-10 06:07 UTC, suinj8 commented
> 브랜치 이름 수정이 필요해보입니다. feature/introdution_page 이런식으로요

추가로 Introduction 시작부분 대문자로 해주세요

2022-05-10 06:39 UTC, LimEunSang commented
> 브랜치 이름 수정이 필요해보입니다. feature/introdution_page 이런식으로요

제가 브랜치 이름에 feature/ 안 붙인지 모르고 작업하고 PR 까지 해놨는데
브랜치 이름을 바꾸면 PR이 사라지더라구요ㅠ

병합하면 브랜치 삭제할꺼라서 이번만 넘어가주실수있나요..
담엔 브랜치 생성할때 이름 신경쓰겠습니다.

2022-05-10 06:43 UTC, closed without merging