Feature/dev article page
AI-Homepage-Practice-Frontend/AI-Homepage pull request #33
Opened 2022-05-10 13:20 UTC by baaaam771

언론보도 페이지 생성했습니다
FeaturePost 컴포넌트 props 명칭을 포괄적으로 명명해서
유동적으로 재활용 할 수 있게 리팩토링 했습니다 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/60038592/167637387-cba85bca-93bf-4f67-b044-bc40db09879a.png">

2022-05-10 14:23 UTC, suinj8 requested changes
주석 시작부에 별2개 말고는 완벽합니다.
작아지면 사진 없어지는것까지 좋네요.
언론보도랑 소식통페이지도 똑같은 컴포넌트를 이용하여
만들면 좋을것 같습니다.

2022-05-10 14:23 UTC, suinj8 commented on src/components/FeaturedPost.js
> +/*
/** 첫줄은 별표 2개에요!

2022-05-10 14:40 UTC, euny0ung commented
LGTM! 화면 줄어들면 사진 없어지는거 아이디어 좋은것 같습니다. 실행해보면서 알게된건데 스크롤을 내린 상태에서 card를 누르면 맨 위로 올라가는 현상이 발생하네요. 제가 만든것도 그런걸보면 원래 있는 mui 기능(?)인것 같아요. 이 부분 문제없을까요?

2022-05-10 14:44 UTC, baaaam771 commented on src/components/FeaturedPost.js
> +/*
넵 수정하겠습니다

2022-05-10 14:47 UTC, baaaam771 commented
> LGTM! 화면 줄어들면 사진 없어지는거 아이디어 좋은것 같습니다. 실행해보면서 알게된건데 스크롤을 내린 상태에서 card를 누르면 맨 위로 올라가는 현상이 발생하네요. 제가 만든것도 그런걸보면 원래 있는 mui 기능(?)인것 같아요. 이 부분 문제없을까요?

해당 현상은 FeaturedPost 컴포넌트 보시면 제가 카드 영역을 클릭할 때 a 태그 기능중에 href로 페이지 이동을 설정해뒀는데요.
페이지를 이동하게 되면 새로고침이 되면서 맨위로 올라가게 되기 때문에 카드를 누르면 맨위로 올라가는 것처럼 보이는것 입니다.
맨위로 올라가는 것을 원하지 않으면 href 부분을 제거하면 되지 않을까 싶습니다

2022-05-10 15:00 UTC, euny0ung commented
> > LGTM! 화면 줄어들면 사진 없어지는거 아이디어 좋은것 같습니다. 실행해보면서 알게된건데 스크롤을 내린 상태에서 card를 누르면 맨 위로 올라가는 현상이 발생하네요. 제가 만든것도 그런걸보면 원래 있는 mui 기능(?)인것 같아요. 이 부분 문제없을까요?
> 
> 해당 현상은 FeaturedPost 컴포넌트 보시면 제가 카드 영역을 클릭할 때 a 태그 기능중에 href로 페이지 이동을 설정해뒀는데요. 페이지를 이동하게 되면 새로고침이 되면서 맨위로 올라가게 되기 때문에 카드를 누르면 맨위로 올라가는 것처럼 보이는것 입니다. 맨위로 올라가는 것을 원하지 않으면 href 부분을 제거하면 되지 않을까 싶습니다

앗 그러네요 다시보니까 제 card는 위로 안올라가네요 피곤해서 잘못본것 같아요 죄송합니다ㅎㅎ..

2022-05-10 15:00 UTC, euny0ung approved these changes

2022-05-10 15:11 UTC, baaaam771 commented
> > > LGTM! 화면 줄어들면 사진 없어지는거 아이디어 좋은것 같습니다. 실행해보면서 알게된건데 스크롤을 내린 상태에서 card를 누르면 맨 위로 올라가는 현상이 발생하네요. 제가 만든것도 그런걸보면 원래 있는 mui 기능(?)인것 같아요. 이 부분 문제없을까요?
> > 
> > 
> > 해당 현상은 FeaturedPost 컴포넌트 보시면 제가 카드 영역을 클릭할 때 a 태그 기능중에 href로 페이지 이동을 설정해뒀는데요. 페이지를 이동하게 되면 새로고침이 되면서 맨위로 올라가게 되기 때문에 카드를 누르면 맨위로 올라가는 것처럼 보이는것 입니다. 맨위로 올라가는 것을 원하지 않으면 href 부분을 제거하면 되지 않을까 싶습니다
> 
> 앗 그러네요 다시보니까 제 card는 위로 안올라가네요 피곤해서 잘못본것 같아요 죄송합니다ㅎㅎ..

아니에요 안그래도 스크롤 제어하는 방법 찾아보고 있었어서 좋은 질문이었어요

2022-05-10 15:56 UTC, suinj8 approved these changes
수정 확인했습니다.
LGTM

2022-05-10 16:45 UTC, euny0ung approved these changes

2022-05-10 17:49 UTC, LimEunSang reviewed
{post.gray_subtitle} 여기서 이렇게 존재하지 않는 객체의 멤버에 접근해도 오류가 안 나네요!? 또 Typography에 글자를 안 넣으면 이 태그는 아예 없는 취급 돼버리는 것도 처음 알았는데, 이 사실들을 이용해서 컴포넌트화 한 FeaturedPost 컴포넌트를 운영위원회 페이지와 언론보도 페이지에 적절하게 사용하는 아이디어가 참 좋은 거 같아요!!

2022-05-10 17:49 UTC, LimEunSang commented on src/components/FeaturedPost.js
> +            <Typography variant="subtitle2" paragraph>
여기 있는 paragraph 속성, 약간의 margin을 주기 위한 용도 말고 다른 이유가 있을까요?

2022-05-10 17:49 UTC, LimEunSang commented on src/pages/notice/Article.js
> + *    운영위원회 dummy data
운영위원회 -> 언론보도

이건 제가 수정해서 commit 할게요.
고맙단 말은 아껴두세요.. 이정도는 센스..

2022-05-10 18:03 UTC, baaaam771 commented on src/pages/notice/Article.js
> + *    운영위원회 dummy data
제대로 확인을 못했네요 감사합니다!

2022-05-10 18:06 UTC, baaaam771 commented on src/components/FeaturedPost.js
> +            <Typography variant="subtitle2" paragraph>
Typography에서 paragraph를 기본 컴포넌트로 자주 사용한다고 하더라고요 
paragraph를 써주면 p 태그 처럼 처리해주는 것으로 알고 있습니다
추가적으로 여백을 줄때 단위를 쫌더 간편하게 처리가 가능하다고 하더라고요

2022-05-10 18:06 UTC, baaaam771 commented on src/components/FeaturedPost.js
> +            <Typography variant="subtitle2" paragraph>
`gutterBottom: {
    marginBottom: '0.35em',
},
paragraph: {
    marginBottom: 16,
},`

2022-05-11 03:02 UTC, LimEunSang approved these changes
답글 확인했습니다. LGTM!

2022-05-11 06:24 UTC, suinj8 requested changes
제가 공지사항 페이지 만들고 머지하면서
이미 폴더 이름을 News로 만들었습니다.
수정 부탁드립니다.
pages/News

2022-05-11 06:24 UTC, suinj8 commented on src/pages/notice/Article.js
> +import { createTheme, ThemeProvider } from "@mui/material/styles";
createTheme과 ThemeProvider는 위에
@mui/material 에도 정의되어 있습니다.

import {
  CssBaseline,
  Grid,
  Container,
  createTheme,
  ThemeProvider,
} from "@mui/material";

이렇게 작성해주시면 보기더 예쁠 것 같아요.

2022-05-11 06:24 UTC, suinj8 commented on src/pages/notice/Article.js
> +const theme = createTheme();
추가적으로 theme을 정의해서 사용하지 않았는데 
왜 추가하신건지 알 수 있을까요?
없어도 출력화면엔 변화 없습니다.

2022-05-11 06:24 UTC, suinj8 commented on src/pages/notice/Article.js
> +    <ThemeProvider theme={theme}>
위와 같은 맥락입니다.

2022-05-11 07:51 UTC, baaaam771 commented on src/pages/notice/Article.js
> +const theme = createTheme();
다크모드 시도해보다가 안지워놨네요 
수정하도록 하겠습니다

2022-05-11 08:02 UTC, baaaam771 commented on src/pages/notice/Article.js
> +const theme = createTheme();
다크모드 시도해보다가 안지워놨네요
수정하도록 하겠습니다

2022-05-11 08:12 UTC, baaaam771 commented
> 제가 공지사항 페이지 만들고 머지하면서 이미 폴더 이름을 News로 만들었습니다. 수정 부탁드립니다. pages/News

<img width="651" alt="image" src="https://user-images.githubusercontent.com/60038592/167801272-f80d746c-75b1-4eaf-b83b-869919217968.png">
현재 pages 안의 폴더가 News만 대문자로 시작해서 이부분에 대해서 논의해보고 수정하겠습니다

2022-05-11 08:19 UTC, baaaam771 commented on src/pages/notice/Article.js
> +    <ThemeProvider theme={theme}>
수정했습니다

2022-05-11 08:19 UTC, baaaam771 commented on src/pages/notice/Article.js
> +const theme = createTheme();
수정했습니다

2022-05-11 10:43 UTC, suinj8 approved these changes
일단 LGTM

2022-05-11 11:06 UTC, merged