Feature/research field page
AI-Homepage-Practice-Frontend/AI-Homepage pull request #42
Opened 2022-05-23 12:32 UTC by euny0ung

연구분야 페이지를 구현했습니다.
파란색이 진한편이라 버튼의 글자가 잘 안보이는것 같아 한단계 낮췄습니다.

![연구분야페이지 완성](https://user-images.githubusercontent.com/56199780/169819775-aa4c3c53-adca-4341-bbb5-7d68a052b6dd.PNG)

2022-05-23 12:43 UTC, euny0ung commented
css 파일은 research 폴더 안에 넣었습니다.

2022-05-23 17:21 UTC, LimEunSang reviewed
디자인 관련해서 신기하고 처음 보는 속성들을 많이 구경합니다..
visible에 id값을 할당해  버튼마다 다른 컴포넌트를 나오게 하는 아이디어 상당히 좋네요!
고생 많이하셨습니다!!

각 분야의 컴포넌트(FildDL, FildML, ...)가 내용만 다르고 똑같은 형식을 띄고 있어서 공통 컴포넌트화하면 훨씬 효율적일 거 같아요. 각 Field 파일을 따로 생성할 필요 없이 내용만 객체 props로 전달하면 하나의 페이지 안에서 모두 선언이 가능해집니다.

2022-05-23 17:21 UTC, LimEunSang commented on src/pages/research/ResearcherFieldPages/FieldDL.js
> +        // backgroundColor: "#f9f9f9"
주석 처리한 코드를 남겨 놓은 이유가 있나요?

2022-05-23 17:21 UTC, LimEunSang commented on src/pages/research/ResearcherFieldPages/FieldDL.js
> +          marginLeft: '70%',
사진을 오른쪽에 배치한 이유가 있나요?

2022-05-24 08:59 UTC, suinj8 requested changes
결국 그리드로 해결하셨군요.
고생하셨습니다.

2022-05-24 08:59 UTC, suinj8 commented on src/pages/research/ResearchField.js
> +  //    랩실 설명
주석 띄어쓰기가 많이 되어있네요.

2022-05-24 08:59 UTC, suinj8 commented on src/pages/research/ResearchField.js
> +            backgroundColor: '#0288d1',
파란색이 좀 진해서 글씨가 선명하지 않은것 같습니다.
배경색이 바뀌면서 글씨색도 흰색으로 바뀌게 하면 어떨까요?

![image](https://user-images.githubusercontent.com/90179555/169992551-43f549d9-1f81-433d-b008-d59e6dd8c470.png)

2022-05-24 10:23 UTC, euny0ung commented on src/pages/research/ResearcherFieldPages/FieldDL.js
> +          marginLeft: '70%',
없습니다! 가운데에 있으면 뭔가 이상해서 오른쪽으로 빼두었습니다

2022-05-30 08:44 UTC, euny0ung commented
말해주신 부분들 전부 수정했습니다. 확인 부탁드려요! 버튼을 눌렀을때 화면이 출력되어야하는데 됐다가 안됐다가 하는 이슈가 있습니다(이슈 46번). 이 부분 고치면 끝입니다..

2022-05-30 15:16 UTC, suinj8 approved these changes
LGTM!

2022-05-30 16:49 UTC, LimEunSang approved these changes
페이지 구현하느라 고생하신게 코드에서 보여요... 정말 수고많으셨어요! 함수 정의도 잘 해서 사용하고, 컴포넌트화도 너무 잘 하셨네요.  밑에 남겨놓은 comment 한 번씩만  확인해주세요! LGTM

2022-05-30 16:49 UTC, LimEunSang commented on src/App.js
> +          <Route path="/researchfield" element={<ResearchField />} />
39번째 줄 지우고 그 자리에 작성해달라고 navigate 브랜치 PR에 글 남겨놨었는데, 신경 못쓰셨나보네요! 병합 이후에 제가 수정할 거 수정하면서 한 번에 수정하겠습니다.

2022-05-30 16:49 UTC, LimEunSang commented on src/pages/research/ResearchField.js
> +  const [contents, setContents] = useState("trans");
변수 명이 'field' 처럼 좀 더 명확했으면 좋았을 거 같아요. 이런 부분도 일단 병합 이후에 제가 고민해서 한 번 수정해보도록 할게요.

2022-05-30 16:49 UTC, LimEunSang commented on src/pages/research/ResearchField.js
> +//임시 사진 경로
제가 알기로 주석처리문 뒤에 한 칸 띄고 주석 작성하는 걸로 알고있어요. 다른 분들도 그렇게 한 거 같아요.
//임시 사진 경로 (x)
// 임시 사진 경로 (o)

이 부분도 일단 병합 이후에 제가 수정할게요!

2022-05-30 16:49 UTC, LimEunSang commented on src/pages/research/ResearchField.js
> +// 버튼 클릭시 나오는 화면에 대한 정보
매우 사소한 거지만 앞으로 코드 작성하실 때 스타일을 통일해주세요!
정해지지 않은 방식에 대해서 상대방의 스타일에 맞춰달라는게 아니라, 예를 들어
//내용 <- 이렇게 작성하기로 마음먹었으면 전부 저렇게 작성해주시고
// 내용 <- 이렇게 작성하기로 마음먹었으면 전부 저렇게 작성해주세요!

결국 refactoring 할 때 다 맞춰야 하는데 그때 작업할 양이 많아지지 않게 하기 위해서요.

2022-05-30 16:49 UTC, LimEunSang commented on src/pages/research/ResearchField.js
> +      {/* 부제목 */}
다음에는 주석으로 구간을 명시하여 나눠줄 때 줄바꿈 해주세요!
일단 머지 이후에 제가 수정할게요!

2022-05-30 16:49 UTC, LimEunSang commented on src/pages/research/ResearchField.js
> +      {contents && selectComponent[contents]}
이 부분은 정말 신기하네요. 난생 처음 보는 형식인데, 객체[맴버] 이렇게 접근하면 맴버에 해당하는 부분만 출력이 되는줄 처음 알았어요. 유용한거 배워갑니다!

2022-05-31 06:29 UTC, euny0ung commented on src/App.js
> +          <Route path="/researchfield" element={<ResearchField />} />
Project 파일에서 한번에 수정했는데 따로해야되는군요 주석 수정하는김에 같이 하겠습니다!!

2022-05-31 09:18 UTC, euny0ung commented on src/pages/research/ResearchField.js
> +      {/* 부제목 */}
ResearchField 파일 주석 띄어쓰기, 구간 나누기 완료하였습니다. 구간 나누기의 경우 줄바꿈을 해도 prettier 때문에 안먹히는(?) 부분이 있어서 그런건 그냥 두었습니다. ex) ResearchField의 303번째 줄

2022-06-01 08:11 UTC, LimEunSang commented on src/pages/research/ResearchField.js
> +      {/* 부제목 */}
확인했습니다

2022-06-04 00:18 UTC, baaaam771 approved these changes
기존 코드에서 중복 되는 거 제거하시고 버튼 이벤트 새로 만들어서 작성하느라 고생많으셨습니다 커밋 전체 내용 보니까 본인이 스스로 로직 생각하셔서 직접 짜신 것 같더라고요 수고하셨어요! LGTM

2022-06-04 03:38 UTC, merged