Feature/professor mock server
AI-Homepage-Practice-Frontend/AI-Homepage pull request #49
Opened 2022-06-15 09:11 UTC by euny0ung

![image](https://user-images.githubusercontent.com/56199780/173790078-23af77f5-749d-440c-8fa5-a29def239013.png)

API에 직급이 없어서 그 부분은 뺐습니다.

2022-06-15 09:56 UTC, LimEunSang requested changes
저번 회의에서 말씀드렸는데,
backend와 실제 연동하기 전까지 mock 서버에서 받아오는 api 정보는 지우지 마시고 주석으로 남겨놔주세요.
어떻게 데이터가 들어오는지 두 눈으로 확인할 수 있게요.

변수 명 lab -> location 이렇게 가독성 있게 잘 바꿔주셨네요!
언급한 부분들 수정해주세요!

2022-06-15 09:56 UTC, LimEunSang commented on src/pages/member/Professor.js
> +  //API로 받아온 정보 저장
이전 코드리뷰에서도 부탁드렸듯이

//주석 내용 (x)
// 주석 내용 (o)

이렇게 작성해주시고


매우 사소한 거지만 앞으로 코드 작성하실 때 스타일을 통일해주세요!
정해지지 않은 방식에 대해서 상대방의 스타일에 맞춰달라는게 아니라, 예를 들어
//내용 <- 이렇게 작성하기로 마음먹었으면 전부 저렇게 작성해주시고
// 내용 <- 이렇게 작성하기로 마음먹었으면 전부 저렇게 작성해주세요!

결국 refactoring 할 때 다 맞춰야 하는데 그때 작업할 양이 많아지지 않게 하기 위해서요.

2022-06-15 13:45 UTC, euny0ung commented on src/pages/member/Professor.js
> +  //API로 받아온 정보 저장
주석, 더미데이터 수정했습니다!!

2022-06-15 15:05 UTC, suinj8 approved these changes
LGTM!

2022-06-15 15:19 UTC, LimEunSang approved these changes
LGTM 고생했습니다!

2022-06-16 00:24 UTC, baaaam771 approved these changes
LGTM 고생하셨습니다!

2022-06-17 06:31 UTC, merged