Feature/apply mock to announcement
AI-Homepage-Practice-Frontend/AI-Homepage pull request #53
Opened 2022-06-18 09:46 UTC by suinj8

Mock API 공지사항 페이지에 적용하였습니다.

- 작성일은 수정일 기준으로 표시하였습니다.
- 작성일은 년-월-일 까지 표기하였습니다.
- 컴퓨터공학부 홈페이지를 참고하여 조회수 추가하였습니다.

2022-06-21 16:57 UTC, LimEunSang requested changes
수정일은 출력 안해줘도 될까요? (수정일도 출력하라고 돌려말하는거 아니고 궁금해서 물어보는거에요)

2022-06-21 16:57 UTC, LimEunSang commented on src/pages/news/Announcement.js
> +// ];
저희가 dummydata로 써놨던 코드를 안지우고 주석처리해놓는 이유가 데이터를 어떻게 받아오는지 확인하기 위해서라고 했잖아요.
확인을 할 수 있으려면 목서버에서 뿌려주는 데이터 형식과 맞춰줘야 합니다. 수정해주세요.
(데이터를 어떻게 받아오는지 확인하는 작업이 필요한 이유는 일단 다른 사람의 목서버를 직접 들어가서 확인이 불가능한 게 첫 번째 이유고, 두 번째 이유는 실수 방지입니다. 백이 설계한 api와 다르게 설계를 했다면 다른 사람의 코드 리뷰를 통해 실수를 검출할 수 있습니다. )

2022-06-21 19:23 UTC, LimEunSang commented on src/pages/news/Announcement.js
> +// ];
그냥 주석처리한 더미데이터 지워버리죠. api 어떻게 받아오는지 코드 내에서 확인할 수 있게 지우지 말고 주석으로 남겨달라고 했었는데 데이터 요청 주소 직접 들어가면 확인 가능하네요.

2022-06-22 04:05 UTC, suinj8 commented
> 수정일은 출력 안해줘도 될까요? (수정일도 출력하라고 돌려말하는거 아니고 궁금해서 물어보는거에요)

수정일 기준으로 표시한다고 써놓았습니다.

첫 작성일을 안적는 것인데 미리보기 페이지니까 가장 최신날짜 기준으로
적용하는것이 좋을거라 생각했습니다.

2022-06-22 07:59 UTC, baaaam771 commented
네이버 블로그랑 카페 게시글 형태 봤는데 날짜는 하나만 표기되어 있는것 같아요
그래서 하나만 표기해도 된다고 생각해요

2022-06-22 08:00 UTC, baaaam771 approved these changes

2022-06-24 15:59 UTC, euny0ung commented
궁금한게 있는데 1일, 5일, 10일에 게시물을 작성했다고 가정하고 5일에 올린 게시물을 11일에 수정하면 1일, 10일, 11일 이렇게 자동정렬되는건가요?? 수정일을 기준으로 정렬된다면 글의 순서가 바뀌니까 최초 작성일을 기준으로 하는게 좋을것 같다고 생각합니다!

2022-06-25 04:38 UTC, suinj8 commented
> 궁금한게 있는데 1일, 5일, 10일에 게시물을 작성했다고 가정하고 5일에 올린 게시물을 11일에 수정하면 1일, 10일, 11일 이렇게 자동정렬되는건가요?? 수정일을 기준으로 정렬된다면 글의 순서가 바뀌니까 최초 작성일을 기준으로 하는게 좋을것 같다고 생각합니다!

api를 받아오므로 자동정렬 될겁니다. 생각해보니 그 문제도 있겠네요.
그렇다면 저도 최초작성일로 하는게 좋아보입니다.

2022-06-26 15:01 UTC, LimEunSang approved these changes
최초 작성일 하나만 출력하는거 내용 확인했고 동의합니다~
dummydata 주석만 지워주세요
LGTM

2022-06-26 15:01 UTC, LimEunSang commented on src/pages/news/Announcement.js
> +// ];
그냥 주석처리한 더미데이터 지워버리죠. api 어떻게 받아오는지 코드 내에서 확인할 수 있게 지우지 말고 주석으로 남겨달라고 했었는데 데이터 요청 주소 직접 들어가면 확인 가능하네요.

2022-06-26 15:43 UTC, euny0ung approved these changes

2022-06-27 13:38 UTC, suinj8 commented on src/pages/news/Announcement.js
> +// ];
알겠습니다.

2022-06-27 13:39 UTC, suinj8 commented
은영님 의견대로 최초 작성일 기준으로 표기하게 수정하였습니다.

2022-06-27 13:43 UTC, merged