feat: apply mock server to article page
AI-Homepage-Practice-Frontend/AI-Homepage pull request #57
Opened 2022-06-20 02:24 UTC by baaaam771

- mock server 데이터 article page에 적용
- infoChannel과 동일

2022-06-21 08:13 UTC, suinj8 approved these changes
LGTM!

2022-06-21 19:17 UTC, LimEunSang requested changes
제가 "* A " 이렇게 코멘트 한 부분 일부러 수정하신건가요??

그리고 아마 그 부분이 수정된 거 때매 지금 현재 이 branch에서 소식통 페이지가 오류나는 거 같아요.

2022-06-21 19:17 UTC, LimEunSang commented on src/components/FeaturedPost.js
> +function FeaturedPost(props) {
* A: 이 부분 일부러 삭제하신 건가요? 제가 수정했었는데

2022-06-21 19:17 UTC, LimEunSang commented on src/components/FeaturedPost.js
> +  const { post } = props;
* A

2022-06-21 19:17 UTC, LimEunSang commented on src/components/FeaturedPost.js
> +      <CardActionArea component="a" href="#">
* A

2022-06-21 19:17 UTC, LimEunSang commented on src/pages/news/Article.js
> +// ];
그냥 주석처리한 더미데이터 지워버리죠. api 어떻게 받아오는지 코드 내에서 확인할 수 있게 지우지 말고 주석으로 남겨달라고 했었는데 데이터 요청 주소 직접 들어가면 확인 가능하네요.

2022-06-22 02:16 UTC, baaaam771 commented on src/pages/news/Article.js
> +// ];
넵 주소로 들어가면 json data 보이는거 알고는 있었는데 PR 할 때 한 페이지 안에서 보기 편하시라고 남겨뒀던거였어요. 수정하도록 하겠습니다!

2022-06-22 02:17 UTC, baaaam771 commented
> 제가 "* A " 이렇게 코멘트 한 부분 일부러 수정하신건가요??
> 
> 그리고 아마 그 부분이 수정된 거 때매 지금 현재 이 branch에서 소식통 페이지가 오류나는 거 같아요.

제가 전에 info channel에 있는 파일 그대로 가져와서 이 오류 생겼던것 같아요 수정하겠습니다!

2022-06-22 05:26 UTC, baaaam771 commented on src/components/FeaturedPost.js
> +      <CardActionArea component="a" href="#">
요청하신 A 부분 복구 했습니다!

2022-06-30 14:26 UTC, euny0ung commented
제가 코드에 코멘트 남긴거 start a review로 해서 안보이시나요?? 안보이는줄 모르고 계속 왜 답이 없으시지 생각했네요 죄송합니다... start a review로 하면 코멘트가 리뷰 남기기 전까지 안보인다고 하네요

2022-07-01 05:38 UTC, baaaam771 commented
> 제가 코드에 코멘트 남긴거 start a review로 해서 안보이시나요?? 안보이는줄 모르고 계속 왜 답이 없으시지 생각했네요 죄송합니다... start a review로 하면 코멘트가 리뷰 남기기 전까지 안보인다고 하네요

코드에 들어가도 코멘트가 안보이는데 혹시 어디에다가다 남겨두셨나요? ㅠㅠ

2022-07-01 12:06 UTC, euny0ung commented
FeaturedPost.js에 했습니다! 왜 안보일까요..

![image](https://user-images.githubusercontent.com/56199780/176891088-2e9636e0-fcd4-448b-a8cf-ced2ee23bbf1.png)

2022-07-04 07:46 UTC, LimEunSang approved these changes
제가 언급한 부분 수정 내역 확인했습니다!
InfoChannel 페이지가 왜 오류가 나는지 봤더니 FeaturedPost를 수정해서 그런거였네요.
InfoChannel 수정 브랜치도 병합하면 자동으로 해결되겠네요.

또한 은영님이 언급하신 부분 내용인데요,
> FeaturedPost.js에 했습니다! 왜 안보일까요..
> 
> ![image](https://user-images.githubusercontent.com/56199780/176891088-2e9636e0-fcd4-448b-a8cf-ced2ee23bbf1.png)

props -> post로 수정하셔야 합니다. 이 부분만 수정해주시면 완벽해보입니다.

(실수로 approve로 review 했는데 request change로 수정을 어떻게 하는지 모르겠네요.)

2022-07-06 05:27 UTC, baaaam771 commented
@euny0ung @LimEunSang  요청하신 부분 변경했습니다!
은영님 코드리뷰 한게 저만 안보이나요? ㅠ

2022-07-10 12:53 UTC, euny0ung approved these changes

2022-07-10 12:53 UTC, euny0ung commented on src/components/FeaturedPost.js
> +              {props.boardName}
이 부분 혹시 post.boardName 인가요?? 실행해보니 props가 정의되지 않았다고 오류 뜨네요

2022-07-15 01:19 UTC, merged