Feature/apply mock to info channel
AI-Homepage-Practice-Frontend/AI-Homepage pull request #66
Opened 2022-06-28 05:53 UTC by baaaam771

수인님이 만들어두셨던 info channel에 
은상님이 세부페이지 넘어가지는 링크 적용했습니다
전체적인 내용은 article channel과 동일합니다

2022-07-04 07:53 UTC, LimEunSang requested changes

2022-07-04 07:53 UTC, LimEunSang commented on src/components/FeaturedPost.js
> +              {props.boardName}
이 부분 props -> post 수정해주세요~

2022-07-04 07:54 UTC, LimEunSang requested changes
작성일 주석 부분도 최신 날짜로 수정해야되요!

2022-07-06 05:34 UTC, baaaam771 commented on src/components/FeaturedPost.js
> +              {props.boardName}
변경했습니다!

2022-07-06 05:34 UTC, baaaam771 commented
> 작성일 주석 부분도 최신 날짜로 수정해야되요!

넵 수정했습니다!

2022-07-12 08:15 UTC, LimEunSang approved these changes
변경 내용 확인하였습니다 고생하셨습니다!
LGTM

2022-07-12 08:31 UTC, euny0ung commented
LGTM!

2022-07-12 08:31 UTC, euny0ung approved these changes

2022-07-14 11:05 UTC, suinj8 approved these changes
LGTM!

2022-07-15 01:09 UTC, merged